services:
  postgresql:
    image: postgres:16-alpine
    container_name: mm-psql
    environment:
      - POSTGRES_DB=matchmaker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data


